# Generated by Django 2.0.2 on 2018-02-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('category', models.CharField(choices=[('Adventurous', 'Adventurous'), ('Classic', 'Classic'), ('Marine', 'Marine')], max_length=25)),
            ],
        ),
    ]


