# Generated by Django 2.1.4 on 2018-12-27 09:25
import json

from django.db import migrations


def load_data_from_file(apps, schema_editor):
    """
    This function loads the departures data from the provided JSON file
    into the DB during the migration process.
    """
    Departure = apps.get_model('departures', 'Departure')

    json_filename = "departures.json"

    with open(json_filename, 'r') as json_file:
        json_data = json.loads(json_file.read())

    for item in json_data:
        departure = Departure.objects.create(name=item['name'],
                                             start_date=item['start_date'],
                                             finish_date=item['finish_date'],
                                             category=item['category'])
        departure.save()


class Migration(migrations.Migration):

    dependencies = [
        ('departures', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data_from_file),
    ]
