# Generated by Django 2.1.4 on 2020-01-03 19:02

from django.db import migrations
import json


def getDepartures(apps, schema_editor):
    with open("departures.json") as json_file:
        data = json.load(json_file)
        Departure = apps.get_model("departures", "Departure")
        db_alias = schema_editor.connection.alias
        for departure in data:
            Departure.objects.using(db_alias).create(name=departure["name"], start_date=departure["start_date"], finish_date=departure["finish_date"], category=departure["category"])


class Migration(migrations.Migration):

    dependencies = [
        ('departures', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(getDepartures)
    ]



